# Generated by Django 3.2.4 on 2023-05-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinarblog', '0002_auto_20230502_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
